# yaml-language-server: $schema=configuration.schema.json
---
tracker:
  options:
    # tracker
    interval: 15
    keep-awake: false
    run-on-startup: true
    show-last-n-weeks: 2
    save-csv-copy: false
    csv-filepath: /backups/

    # calendar
    linked-calendar: none
    use-calendar-appointments: true
    appointment-category-exclusions: [Planned Work, Non-Working]

    # jira
    jira-type: cloud # Just to emphasise that Server is not supported
    jira-filter: "" # sprint IN openSprints() AND assignee = currentUser()
    post-to-jira: false

    # slack
    post-to-slack: false

    # monday.com
    monday-filter: |-
      query {
        boards(ids: [123]) {
          name
          items_page(
            limit: 500
            query_params: {
              operator: and
              rules: [
                {
                  column_id: "person"
                  compare_value: ["assigned_to_me"]
                }
              ]
            }
          ) {
            items {
              name
              parent_item {name}
            }
          }
        }
      }
