name: issue-create-actions
run-name: Issue create actions

on:
  issues:
    types:
      - opened

jobs:
  raise-jira-ticket:
    name: Raise Jira Ticket
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ›ï¸ Checkout
      uses: actions/checkout@master

    - name: ğŸ”‘ Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: ğŸ« Create Jira Issue
      id: create-jira-issue
      uses: atlassian/gajira-create@v3
      with:
        project: DATA
        issuetype: Bug
        summary: ${{ github.event.issue.title }}
        description: ${{ github.event.issue.body }}

    - name: Log created issue
      run: echo "Issue ${{ steps.create-jira-issue.outputs.issue }} was created"
